[package]
name = "bitmap_crusher"
version = "0.0.1"
authors = ["Rose Midford <wwwwolf@iki.fi>"]
edition = "2024"
license = "MIT"

[dependencies]
png = "0.17.16"
arguments = "0.8.0"
# hexdump = "0.1.2"